# --- Basic options --- #

# Name of website
title: Base space

# Short description of your site
description: I am a PhD student at University of Sao Paulo, investigating quantum physics of thermodynamics.

# Your name to show in the footer
author: Rodolfo R. Soldati

# GitHub Pages theme
theme: jekyll-theme-minimal

# Logo
logo: "./assets/img/me.jpg"

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

# # Default YAML values (more information on Jekyll's site)
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       comments: true  # add comments to all blog posts
#       social-share: true # add social media sharing buttons to all blog posts
#       readtime: false # add estimated reading time on all blog posts
#   -
#     scope:
#       path: "" # all files
#     values:
#       layout: "page"
#       show-avatar: true

# # Exclude these files from production site
# exclude:
#   - CHANGELOG.md
#   - CNAME
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE
#   - README.md
#   - screenshot.png
#   - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
