# --- Basic options --- #
# See https://github.com/pages-themes/minimal
# for more

# Name of website
title: Base space

# Short description of your site
description: I am a PhD fellow at the University of Stuttgart and jointly at the University of São Paulo, investigating quantum thermodynamics with a view towards information and its use in quantum matter and high-energy physics.

# Your name to show in the footer
author: Rodolfo R. Soldati
email: rsoldati@usp.br

# GitHub Pages theme
theme: jekyll-theme-minimal

# Logo
logo: "./assets/img/me.jpg"

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
