# --- Basic options --- #

# Name of website
title: Base space

# Short description of your site
description: The website of Rodolfo R. Soldati

# Your name to show in the footer
author: Rodolfo R. Soldati

# GitHub Pages theme
theme: jekyll-theme-minimal

# Logo
logo: "./assets/img/me.jpg"

# --- List of links in the navigation bar --- #

# navbar-links:
#   About Me: "aboutme"
#   Resources:
#     - Beautiful Jekyll: "https://beautifuljekyll.com"
#     - Learn markdown: "https://www.markdowntutorial.com/"
#   Author's home: "https://deanattali.com"

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# # --- You don't need to touch anything below here (but you can if you want) --- #

# # Output options (more information on Jekyll's site)
# timezone: "America/Vancouver"
# markdown: kramdown
# highlighter: rouge
# permalink: /:year-:month-:day-:title/
# paginate: 5

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

# # Default YAML values (more information on Jekyll's site)
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       comments: true  # add comments to all blog posts
#       social-share: true # add social media sharing buttons to all blog posts
#       readtime: false # add estimated reading time on all blog posts
#   -
#     scope:
#       path: "" # all files
#     values:
#       layout: "page"
#       show-avatar: true

# # Exclude these files from production site
# exclude:
#   - CHANGELOG.md
#   - CNAME
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE
#   - README.md
#   - screenshot.png
#   - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
