# --- Basic options --- #

# Name of website
title: Base space

# Short description of your site
description: I am a PhD fellow at the University of São Paulo and at the University of Stuttgart, investigating quantum thermodynamics with a view towards information and its use in quantum matter and high-energy physics.

# Your name to show in the footer
author: Rodolfo R. Soldati

# GitHub Pages theme
theme: jekyll-theme-minimal

# Logo
logo: "./assets/img/me.jpg"

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
